GRADECARD_SPREADSHEET_ID = "1_HXK9ak-IGKpxvJ0SlkjOWnPCNe3LKAxFk_o3OSVFac"

BASE_STUDENT_SPREADSHEET_ID = "1GVnTkbvYpV-jQD_TCUb7DtJNmV_-qT45pxTRsGkHhAs"
STUDENT_CARDS_FOLDER_ID = "13ZSTE4hkMWh55t2mZexvWTh37V11R2sK"

BASE_TA_SPREADSHEET_ID = None
TA_CARDS_FOLDER_ID = None

GRADESCOPE_COURSE_ID = ""
