GRADECARD_SPREADSHEET_ID = "1qxbNPXgWCuomklENmmZuSGZBMr0FL3WsnL09H-DgsE8"

BASE_STUDENT_SPREADSHEET_ID = ""
STUDENT_CARDS_FOLDER_ID = ""

BASE_TA_SPREADSHEET_ID = None
TA_CARDS_FOLDER_ID = None

GRADESCOPE_CLASS_ID = ""
